// Or use @baseScript
class Step1Code extends PluginStep {
    def stepName = '<autogenerated> step1'
    def procedureName = 'procedure name'

    def run() {
        // Generated
        def parameters = getParameters() // implemented in the framework
        def configuration = getConfiguration(parameters.config) // implemented in the framework

        def plugin = new GlassfishPlugin()
        try {
            def response = plugin.stepDeploy(parameters, configuration)
            processResponse(response)
        } catch (Throwable e) {
            setSummary(e.message)
            failWithCode(-1)
        }
    }
}


def step = new Step1Code()
step.run()
